### ISSUE TITLE
Access to repos -mentor swoc

### ISSUE THREAD

**Issue by ASLManasa** [PatternHouse/Join_PatternHouse#34]
git hub :https://github.com/ASLManasa
git_hub_id : ASLManasa

repos I want to mentor
C-PatternHouse
CPlusPlus-PatternHouse 
Java-PatternHouse
JavaScript-PatternHouse 
Python-PatternHouse

**Comment by ChlorinePentoxide** [comment]
@aryashah2k will help you with the SWOC contributions. An invite will be sent soon to join our organization. Thank you very much for checking out our project.

**Comment by aryashah2k** [comment]
Invite sent and Maintainer access given to the mentioned repositories.
Reggarding any queries related to mentoring, please use the following discussions page instead of swoc discord server since I am not that active over there.
Tag me in your discussions for quick response.

https://github.com/PatternHouse/guidelines/discussions/15

**Comment by ASLManasa** [comment]
@aryashah2k I dont have editing access to the sheet.
